#ifndef PROTOCOLO_H_
#define PROTOCOLO_H_

#include "shared.h"

typedef enum {
	// Agregar los tipos de operaciones para todo el sistema aca:
	DESCONEXION = -1,
	ELEMENTOS_CONSOLA,
	DEBUG,
	DISPATCH_PCB,
	FIN_POR_EXIT,
	SIGUIENTE_PROCESO,
	INTERRUPT,
	OP_PANTALLA,
	OP_DISCO,
	OP_TECLADO,
	OP_IMPRESORA,
	TIEMPOS_IO,
	RESPUESTA_PANTALLA,
	RESPUESTA_TECLADO,
	INTERRUPCION_QUANTUM,
	DESALOJO_QUANTUM,
	CREAR_ESTRUCTURAS_MEMORIA,
	RESPUESTA_INDICES_T_PS, // T_PS = Tabla de paginas
	PAGE_FAULT_CPU,  // MENSAJE QUE MANDA CPU A KERNEL
	PAGE_FAULT_MEMORIA, // MENSAJE QUE MANDA LA MEMORIA A CPU
	PAGINA_SOLICITADA, // MENSAJE QUE MANDA KERNEL A MEMORIA
	PAGINA_ENCONTRADA, // MENSAJE QUE MANDA MEMORIA A KERNEL EN RESPUESTA A PAGINA_SOLICITADA.
	NUMERO_DE_MARCO_MEMORIA,
	ACCESO_A_MEMORIA,
	LECTURA_MEMORIA,
	VALOR_LECTURA_MEMORIA,
	ESCRITURA_MEMORIA,
	OK_ESCRITURA_MEMORIA,
	SEGMENTATION_FAULT,
	HANDSHAKE_MEMORIA_CPU
} op_code;

typedef struct {
    int fd;
    char* server_name;
} t_manejar_conexion_args;

//////////// MENSAJES /////////////
bool send_debug(int fd);

// ELEMENTOS_CONSOLA
bool send_elementos_consola(int, t_list*);
bool recv_elementos_consola(int, t_list**);

#endif
